name: Build Geode Mod

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Geode
        uses: geode-sdk/build-geode-mod@v1

      - name: Build
        run: geode build
